services:
- type: web
  name: kibana
  env: docker
  dockerfilePath: ./esDockerfile
  plan: standard plus
  envVars:
  - key: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch1:9200"
- type: pserv
  name: elasticsearch1
  env: docker
  plan: standard plus
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 10
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
  
